### ISSUE TITLE
Forge port ?

### ISSUE THREAD

**Issue by RetroAndDev** [Fusion-Flux/Portal-Cubed-Rewrite#19]
Hi !
Great mod, but why on Quilt ? Fabric or forge are most used. I really what to play this mod with my favourites Forge mod. Any forge/fabric port to come ?

**Comment by Fusion-Flux** [comment]
For alpha 3 we are porting to multiloader 1.21 and will support Quilt, Fabric, and Neoforge you can find more info about the current alphas in our discord including downloads.

**Comment by RetroAndDev** [comment]
> For alpha 3 we are porting to multiloader 1.21 and will support Quilt, Fabric, and Neoforge you can find more info about the current alphas in our discord including downloads.

Joined ! Can't wait to play on Neoforged 1.21 ! The best portal mod I have seen for far. Great work
